token: token.txt
blacklist: blacklist.txt
prefix: '-'
cogs:
  - cogs.config
  - cogs.activity
  - cogs.core
  - cogs.mcq-game
  - cogs.misc
  - cogs.potd
  - cogs.suggestions
potd_sheet: '10X0-CCSv7FenZP1YaKlDSE-PD4LSZAgpzT5Rs9F8hvA'
paradox_id: 419356082981568522
potd_channel: 537763636161150976
potd_role: 561876362776936459
helper_lounge: 561813381716377610
mods_guild: 533153217119387658
log_channel: 559964001724006400
suggestion_channel: 713659894745530479
suggestion_discussion_channel: 533162921715302400
suggestion_role: 722259030298329098
staff: {281300961312374785, 269634843468496906, 414141673514467341, 268970368524484609, 262615117018038272, 300065144333926400, 541318134699786272}
active_role: 717919153092034641
daily_active_threshold: 10
weekly_active_threshold: 4
activity_sheet: '1oxqhse2IJjPbSPy08PYs-iPLg-uRtE5oKqZ6WMurfFU'
welcome_channel: 671277003168677889
lounge_channel: 533153217119387660
roles_channel: 671639229293395978
unverified_role: 563807131275493443
verif_emoji: 564272059610431508
suggestion_sheet: '1PaaBuj7httWJX5go5taMWrhzX3jf5oJ1GNqHFp5gWuA'
tags_sheet: '1ITwXFYSrlw_asQ1lGJusE-w0xT50Mmy__0yxl2URqHI'