token: token.txt
blacklist: blacklist.txt
prefix: '-'
cogs:
  - cogs.config
  - cogs.activity
  - cogs.core
  - cogs.invites
  - cogs.mcq-game
  - cogs.misc
  - cogs.potd
  - cogs.suggestions
  - cogs.mathjams
  - cogs.well
  - cogs.menus
  - cogs.suggest-confirm
potd_sheet: '10X0-CCSv7FenZP1YaKlDSE-PD4LSZAgpzT5Rs9F8hvA'
potd_sheet_id_col: 0
potd_sheet_date_col: 1
potd_sheet_day_col: 2
potd_sheet_curator_col: 3
potd_sheet_source_col: 4
potd_sheet_genre_col: 5
potd_sheet_difficulty_col: 6
potd_sheet_tags_col: 7
potd_sheet_statement_col: 8
potd_sheet_hint1_col: 9
potd_sheet_hint2_col: 10
potd_sheet_hint3_col: 11
potd_message_id_col: 13
potd_proposal_sheet: '1Nt3dGyAN5L8TRAcJFkOyoC7kDfaZ7fpawhUGgWzl56A'
potd_forum: 1020855322006540428
potd_proposal_forum: 1104681491964891156
potd_proposal_forum_tag_pending: 1104681817505800213
potd_proposal_forum_tag_accepted: 1104681867019567135
potd_proposal_forum_tag_rejected: 1104681923537805372
paradox_id: 419356082981568522
staffmail_id: 696261358932721694
potd_channel: 537763636161150976
potd_discussion_channel: 533159339968692225
potd_role: 561876362776936459
helper_lounge: 561813381716377610
tech_garage: 880061238753771561
mods_guild: 533153217119387658
log_channel: 559964001724006400
bot_spam_channel: 537818427675377677
staff_bot_spam_channel: 566364247584669721
suggestion_channel: 713659894745530479
tech_suggestion_channel: 1093374416810950687
mod_role: 558563826891751425
tech_role: 671678617495011347
suggestion_role: 722259030298329098
suggestion_no_notify: 743957659103002634
staff: {281300961312374785, 262615117018038272, 300065144333926400, 541318134699786272, 527550242149761046, 329956567132930048, 456178848745259009, 192464577294761984}
troll: {}
active_role: 717919153092034641
active_threshold: 1500
daily_active_threshold: 10
days_active_threshold: 7
period_length: 14
activity_sheet: '1oxqhse2IJjPbSPy08PYs-iPLg-uRtE5oKqZ6WMurfFU'
welcome_channel: 671277003168677889
new_people_channel: 785066771928449025
lounge_channel: 533153217119387660
roles_channel: 671639229293395978
unverified_role: 563807131275493443
verif_emoji: 564272059610431508
suggestion_sheet: '1PaaBuj7httWJX5go5taMWrhzX3jf5oJ1GNqHFp5gWuA'
tags_sheet: '1ITwXFYSrlw_asQ1lGJusE-w0xT50Mmy__0yxl2URqHI'
mod_vote_chan: 582915500254691328
warn_channel: 739993490108448798
muted_role: 565820528435396619
muted_channel: 565824284669509642
mathjams_channel: 621548930894921749
mathjams_timeslot_a: 880755868822536192
mathjams_timeslot_b: 880756210800922686
mathjams_timeslot_c: 880756539789570089
well_manager_role: 887344625562558496
problem_curator_role: 537768046903951370
well_channel: 954687946697637908
well_sheet: '1eI2PzhwFzPJKEXskpG_ynY1SZYCxpU8eK_zGUH5SMxE'
